backend:
  name: git-gateway
  branch: master
media_folder: "src/static/images"
public_folder: "/images"
collections:
  - name: "notes"
    label: "Notes"
    folder: "src/content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish date",
          name: "datePublished",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: false,
        }
      - {
          label: "Last updated",
          name: "dateUpdated",
          widget: "datetime",
          default: "",
          dateFormat: "YYYY-MM-DD",
          timeFormat: false,
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
